{{- if .Values.query.enabled -}}
apiVersion: monitoring.whizard.io/v1alpha1
kind: Query
metadata:
  name: {{ include "whizard.query.crname" . }}
  namespace: {{ include "whizard.namespace" . }}
  labels:
    {{- if .Values.query.serviceReference }}
    "monitoring.whizard.io/service": "{{ .Values.query.serviceReference.namespace }}.{{ .Values.query.serviceReference.name }}"
    {{- else if .Values.service.enabled }}
    "monitoring.whizard.io/service": "{{ include "whizard.namespace" . }}.{{ include "whizard.service.crname" . }}"
    {{- end }}
    {{- include "whizard.labels" . | nindent 4 }}
spec:
  {{- with .Values.query.replicaLabelNames }}
  replicaLabelNames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{ if .Values.query.genSignedCert }}
  webConfig:
    httpServerTLSConfig:
      certSecret:
        name: {{ include "whizard.query.crname" . }}-query-tls-assets
        key: tls.crt
      keySecret:
        name: {{ include "whizard.query.crname" . }}-query-tls-assets
        key: tls.key
  {{- else }}
  {{- with .Values.query.httpServerTLSConfig }}
  webConfig:
    httpServerTLSConfig:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- end }}
{{- with .Values.query.additionalConfig }}
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- with .Values.query.additionalConfigString }}
  {{- tpl . $ | nindent 2 }}
{{- end }}
{{- end }}
