
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusters.kubesphere.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - alertingrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - rulegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - service
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - storage
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - stores/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - stores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - verbs=get
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - tenants/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - tenants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosreceiveingestors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosreceiveingestors/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosreceiveingestors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosrulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosrulers/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.paodin.io
  resources:
  - thanosrulers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
