{{- if .Values.router.enabled -}}
apiVersion: monitoring.whizard.io/v1alpha1
kind: Router
metadata:
  name: {{ include "whizard.router.crname" . }}
  namespace: {{ include "whizard.namespace" . }}
  labels:
    {{- if .Values.router.serviceReference }}
    "monitoring.whizard.io/service": "{{ .Values.router.serviceReference.namespace }}.{{ .Values.router.serviceReference.name }}"
    {{- else if .Values.service.enabled }}
    "monitoring.whizard.io/service": "{{ include "whizard.namespace" . }}.{{ include "whizard.service.crname" . }}"
    {{- end }}
    {{- include "whizard.labels" . | nindent 4 }}
spec:
  {{ if .Values.router.genSignedCert }}
  webConfig:
    httpServerTLSConfig:
      certSecret:
        name: {{ include "whizard.router.crname" . }}-router-tls-assets
        key: tls.crt
      keySecret:
        name: {{ include "whizard.router.crname" . }}-router-tls-assets
        key: tls.key
  {{- else }}
  {{- with .Values.router.httpServerTLSConfig }}
  webConfig:
    httpServerTLSConfig:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- end }}
{{- with .Values.router.additionalConfig }}
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- with .Values.router.additionalConfigString }}
  {{- tpl . $ | nindent 2 }}
{{- end }}
{{- end }}
