{{- if and (.Values.selfMonitor.enabled) (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") -}}
{{- $components := tuple "compactor" "query" "ingester" "store" "ruler" "router" }}
{{- range $index, $component := $components }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "whizard.fullname" $ }}-{{ $component }}
  namespace: {{ include "whizard.namespace" $ }}
  labels:
    {{- include "whizard.labels" $ | nindent 4 }}
spec:
  endpoints:
  - honorLabels: true
    interval: 1m
    port: http
    scheme: http
    scrapeTimeout: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $component }}
{{- end }}
{{- end -}}